name: Build and Publish DHI RC

env:
  app: fuxa
  version: rc1
  # for available platforms see output of a previous run -
  # ie the "Setup Docker BuildX" / "Inspect Builder" section
  # has eg "node_platforms": "linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  # but the platforms must also be included in the os image chosen -
  # eg the ubuntu image doesn't include linux/arm/v6.
  platforms: linux/amd64,linux/arm64,linux/arm/v7

on: workflow_dispatch
  #push:
  #  branches:
  #    - master

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU emulator
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ env.platforms }}
          tags: frangoteam/${{ env.app }}:${{ env.version }}